---
title: "Figure 6"
author: "Ludvig Larsson"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(STutility)
```

Load Seurat object

```{r}

BN <- readRDS("../../doc/analysis/R_objects/mBone_Seurat_object_filtered")

```


Mask images

```{r}

#BN <- MaskImages(BN, verbose = TRUE, compactness = 0.5)
BN@tools$Staffli@rasterlists$masked <- NULL
BN@tools$Staffli@rasterlists$masked.masks <- NULL
BN@tools$Staffli@rasterlists$processed <- NULL
BN@tools$Staffli@rasterlists$processed.masks <- NULL

```


Warp images

```{r}

BN <- WarpImages(BN, transforms = list("2" = list(angle = -110), "4" = list(angle = -50)))

# Export H&E
for (i in c("2", "4")) {
  im <- GetStaffli(BN)@rasterlists$processed[[i]]
  dims <- GetStaffli(BN)@dims[[i]]
  jpeg(filename = paste0(i, "_processed.jpeg"), width = dims$width, dims$height)
  par(mar=c(0,0,0,0))
  plot(im)
  dev.off()
}

```

Plot selected area

```{r}

limits_list <- list("4" = c(x_start = 480, y_start = 330, x_end = 480 + 1100, y_end = 330 + 1100),
                    "2" = c(x_start = 624, y_start = 621, x_end = 624 + 1150, y_end = 621 + 1150))
factor_limits <- apply(BN@reductions$NMF@cell.embeddings, 2, max)

factorplots <- setNames(lapply(c("2", "4"), function(i) {
  
  # Get meta data and coordinates
  gg <- cbind(BN[[]], GetStaffli(BN)@meta.data, BN@reductions$NMF@cell.embeddings)
  gg <- subset(gg, sample == i) %>%
    reshape2::melt(measure.vars = colnames(BN@reductions$NMF@cell.embeddings)) %>%
    group_by(variable) %>%
    mutate(alpha = scales::rescale(value))
  dims <- GetStaffli(BN)@dims[[i]]
  
  # Get H&E image
  im <- GetStaffli(BN)@rasterlists$processed[[paste0(i)]]
  sf <- nrow(im)/dims$height
  im <- im[limits_list[[i]]["y_start"]:limits_list[[i]]["y_end"]*sf, limits_list[[i]]["x_start"]:limits_list[[i]]["x_end"]*sf]
  g <- grid::rasterGrob(im, width = unit(1, "npc"), height = unit(1, "npc"), interpolate = TRUE)
  
  # Create plots
  plots <- lapply(colnames(BN@reductions$NMF@cell.embeddings), function(fctr) {
    p <- ggplot() +
      annotation_custom(g, -Inf, Inf, -Inf, Inf) +
      geom_point(data = subset(gg, variable == fctr), aes(warped_x, dims$height - warped_y, fill = value), 
                 size = 1.5, alpha = subset(gg, variable == fctr)$alpha, shape = 21, stroke = 0) +
      theme_void() +
      scale_x_continuous(expand = c(0, 0), limits = c(limits_list[[i]]["x_start"], limits_list[[i]]["x_end"])) +
      scale_y_continuous(expand = c(0, 0), limits = c(dims$height - limits_list[[i]]["y_end"], dims$height - limits_list[[i]]["y_start"])) +
      labs(fill = "factor\nactivity") +
      scale_fill_gradientn(colours = c("darkblue", "cyan", "yellow", "red", "darkred"), limits = c(0, factor_limits[fctr]))
  
    if (i == "2") {
      p <- p +
        theme(legend.position = "top", 
            legend.title = element_text(size = 14, colour = "black"), 
            legend.text = element_text(color = "black", size = 12), plot.margin = margin(t = 0, r = 0, b = 3, l = 0))
    } else {
      p <- p + 
        theme(legend.position = "none")
    }
    
    p <- ggrastr::rasterize(p, layers = "Point", dpi = 300)
    return(p)
  })
  plots <- setNames(plots, nm = colnames(BN@reductions$NMF@cell.embeddings))
  return(plots)
}), nm = c("2", "4"))


factorloadings <- setNames(lapply(1:30, function(fctr) {
  p <- FactorGeneLoadingPlot(BN, factor = fctr, topn = 20) +
    theme(axis.title = element_blank(), axis.text = element_text(size = 14, color = "black"))
  return(p)
}), nm = paste0("factor_", 1:30))

```

## Figure 4
***

```{r}

design <- c(
  patchwork::area(1, 1, 1, 1),
  patchwork::area(2, 1, 2, 1),
  patchwork::area(3, 1, 3, 1),
  patchwork::area(1, 2, 1, 2),
  patchwork::area(2, 2, 2, 2),
  patchwork::area(3, 2, 3, 2),
  patchwork::area(1, 3, 1, 3),
  patchwork::area(2, 3, 2, 3),
  patchwork::area(3, 3, 3, 3),
  patchwork::area(1, 4, 1, 4),
  patchwork::area(2, 4, 2, 4),
  patchwork::area(3, 4, 3, 4),
  
  patchwork::area(4, 1, 4, 1),
  patchwork::area(5, 1, 5, 1),
  patchwork::area(6, 1, 6, 1),
  patchwork::area(4, 2, 4, 2),
  patchwork::area(5, 2, 5, 2),
  patchwork::area(6, 2, 6, 2),
  patchwork::area(4, 3, 4, 3),
  patchwork::area(5, 3, 5, 3),
  patchwork::area(6, 3, 6, 3)
)

p <- factorplots$`2`$factor_12 +
  factorplots$`4`$factor_12 +
  factorloadings$factor_12 +
  factorplots$`2`$factor_2 +
  factorplots$`4`$factor_2 +
  factorloadings$factor_2  +
  factorplots$`2`$factor_1 +
  factorplots$`4`$factor_1 +
  factorloadings$factor_1 +
  factorplots$`2`$factor_11 +
  factorplots$`4`$factor_11 +
  factorloadings$factor_11  +
  factorplots$`2`$factor_16 +
  factorplots$`4`$factor_16 +
  factorloadings$factor_16 +
  factorplots$`2`$factor_6 +
  factorplots$`4`$factor_6 +
  factorloadings$factor_6  +
  factorplots$`2`$factor_7 +
  factorplots$`4`$factor_7 +
  factorloadings$factor_7 +
  patchwork::plot_layout(design = design, heights = c(1.1, 1, 1.4, 1.1, 1, 1.4))

pdf(file = "figure_6_patchwork.pdf", width = 15, height = 18)
print(p)
dev.off()

```


### Add bone annotations
***

```{r}

# Read annotations
ann.files <- list.files("../../sheets/bone_annotations", full.names = TRUE)
annotations <- do.call(rbind, lapply(seq_along(ann.files), function(i) {
  f <- ann.files[i]
  ann <- read.csv(f, check.names = FALSE)
  rownames(ann) <- paste0(ann$Barcode, "_", i)
  ann$section_id <- i
  return(ann)
}))

annotations <- annotations %>% mutate(labels = case_when(`mouse growth plate` == "hypertrophic" ~ "hypertrophic zone",
                                                         `mouse growth plate` == "pre-Hypertrophic" ~ "pre-hypertrophic zone",
                                                         `mouse growth plate` == "pre-Hypertrophic zone" ~ "pre-hypertrophic zone",
                                          `mouse growth plate` == "proliferative" ~ "proliferative zone",
                                          `mouse growth plate` == "resting" ~ "resting zone",
                                          TRUE ~ `mouse growth plate`))

BN$annotation <- annotations[colnames(BN), "labels"]

```



## Figure 4 alt. 2
***

Plot selected area

```{r}

limits_list <- list("4" = c(x_start = 480, y_start = 330, x_end = 480 + 1100, y_end = 330 + 1100),
                    "2" = c(x_start = 624, y_start = 621, x_end = 624 + 1150, y_end = 621 + 1150))
gg <- cbind(BN[[]], GetStaffli(BN)@meta.data, BN@reductions$NMF@cell.embeddings) %>%
    reshape2::melt(measure.vars = colnames(BN@reductions$NMF@cell.embeddings)) %>%
    group_by(variable) %>%
    mutate(value = ifelse(value < quantile(value, 0.99), value, quantile(value, 0.99)))
factor_limits <- gg %>%
    summarize(max = max(value))
factor_limits <- setNames(factor_limits$max, nm = factor_limits$variable)

# Factor plots
factorplots <- setNames(lapply(c("2", "4"), function(i) {
  
  # Get meta data and coordinates
  gg <- subset(gg, sample == i) %>%
    group_by(variable) %>%
    mutate(alpha = scales::rescale(value, to = c(0, 1)))
  dims <- GetStaffli(BN)@dims[[i]]
  
  # Get H&E image
  im <- GetStaffli(BN)@rasterlists$processed[[paste0(i)]]
  sf <- nrow(im)/dims$height
  im <- im[limits_list[[i]]["y_start"]:limits_list[[i]]["y_end"]*sf, limits_list[[i]]["x_start"]:limits_list[[i]]["x_end"]*sf]
  g <- grid::rasterGrob(im, width = unit(1, "npc"), height = unit(1, "npc"), interpolate = TRUE)
  
  # Create plots
  plots <- lapply(colnames(BN@reductions$NMF@cell.embeddings), function(fctr) {
    p <- ggplot() +
      annotation_custom(g, -Inf, Inf, -Inf, Inf) +
      geom_point(data = subset(gg, variable == fctr), aes(warped_x, dims$height - warped_y, fill = value), 
                 size = 1.4, alpha = subset(gg, variable == fctr)$alpha, shape = 21, stroke = 0) +
      theme_void() +
      scale_x_continuous(expand = c(0, 0), limits = c(limits_list[[i]]["x_start"], limits_list[[i]]["x_end"])) +
      scale_y_continuous(expand = c(0, 0), limits = c(dims$height - limits_list[[i]]["y_end"], dims$height - limits_list[[i]]["y_start"])) +
      labs(fill = "", y = gsub(pattern = "_", replacement = " ", x = fctr)) +
      scale_fill_gradientn(colours = viridis::viridis(n = 11), limits = c(0, factor_limits[fctr])) +
      guides(fill = guide_colorbar(title.position = "bottom", title.vjust = 1))
  
    if (i == "4") {
      p <- p +
        theme(legend.position = "right", 
            legend.title = element_text(size = 14, colour = "black", angle = 90), 
            legend.text = element_text(color = "black", size = 10), 
            plot.margin = margin(t = 0, r = 0, b = 3, l = 10), 
            legend.key.height = unit(0.4, 'cm'),
            legend.key.width = unit(0.5, 'cm'))
    } else {
      p <- p + 
        theme(legend.position = "none", axis.title.y = element_text(colour = "black", size = 14, angle = 90))
    }
    
    p <- ggrastr::rasterize(p, layers = "Point", dpi = 300)
    return(p)
  })
  plots <- setNames(plots, nm = colnames(BN@reductions$NMF@cell.embeddings))
  return(plots)
}), nm = c("2", "4"))


# Create heatmap
library(zeallot)
c(df1, df2) %<-% SummarizeAssocFeatures(BN, features.return = 7, dims = c(12, 2, 1, 11, 16, 6, 7))
colnames(df2) <- gsub(pattern = "_", replacement = " ", x = colnames(df2))
gheat <- swne::ggHeat(m = df2[rev(df1$feature), ], rescaling = "column") +
  scale_fill_gradientn(colours = RColorBrewer::brewer.pal(n = 9, name = "Blues")) +
  scale_y_discrete(position = "right") +
  scale_x_discrete(position = "top") +
  labs(fill = "gene\nweight") +
  theme(axis.text.x = element_blank(), 
        axis.text.y = element_text(colour = "black", size = 12), 
        legend.text = element_text(colour = "black", size = 12), 
        legend.title = element_text(colour = "black", size = 12),
        plot.margin = margin(0,0,0,0), legend.position = c(0.8, 0.8))

# Create annotations plot
annplots <- setNames(lapply(c("2", "4"), function(i) {
  
  # Get meta data and coordinates
  gg <- cbind(BN[[]], GetStaffli(BN)@meta.data)
  gg <- subset(gg, sample == i)
  gg <- subset(gg, annotation != "")
  dims <- GetStaffli(BN)@dims[[i]]
  gg$annotation <- factor(gg$annotation, levels = c("articular cartilage", "hypertrophic zone", "pre-hypertrophic zone",
                                                    "proliferative zone", "resting zone", "SOC-adjacent resting zone", "SOC"))
  
  # Get H&E image
  im <- GetStaffli(BN)@rasterlists$processed[[paste0(i)]]
  sf <- nrow(im)/dims$height
  im <- im[limits_list[[i]]["y_start"]:limits_list[[i]]["y_end"]*sf, limits_list[[i]]["x_start"]:limits_list[[i]]["x_end"]*sf]
  g <- grid::rasterGrob(im, width = unit(1, "npc"), height = unit(1, "npc"), interpolate = TRUE)
  
  # Create plots
  p <- ggplot() +
    annotation_custom(g, -Inf, Inf, -Inf, Inf) +
    geom_point(data = gg, aes(warped_x, dims$height - warped_y, fill = annotation), 
               size = 1.7, shape = 21, stroke = 0) +
    theme_void() +
    scale_x_continuous(expand = c(0, 0), limits = c(limits_list[[i]]["x_start"], limits_list[[i]]["x_end"])) +
    scale_y_continuous(expand = c(0, 0), limits = c(dims$height - limits_list[[i]]["y_end"], dims$height - limits_list[[i]]["y_start"])) +
    labs(fill = "") +
    scale_fill_manual(values = setNames(c("#332288", "#88CCEE", "#44AA99", "#117733", "#DDCC77", "#AA4499", "#f58231"), 
                 nm = c("articular cartilage", "hypertrophic zone", "pre-hypertrophic zone", "proliferative zone", 
                        "resting zone", "SOC-adjacent resting zone", "SOC"))) +
    guides(fill = guide_legend(title.position = "top", title.hjust = 0.5, ncol = 3, override.aes = list(size = 4)))

  if (i == "4") {
    p <- p +
      theme(legend.position = "top", 
          legend.title = element_text(size = 12, colour = "black"), 
          legend.text = element_text(color = "black", size = 10), 
          plot.margin = margin(t = 0, b = 0, l = 0, r = 10), 
          legend.key.height = unit(0.5, 'cm'),
          legend.key.width = unit(0.5, 'cm'))
  } else {
    p <- p + 
      theme(legend.position = "none", plot.margin = margin(t = 0, b = 0, l = 0, r = 10))
  }
  
  p <- ggrastr::rasterize(p, layers = "Point", dpi = 300)
  return(p)
}), nm = c("2", "4"))

# Export annotations
pdf(file = "annotations.pdf", width = 7, height = 4.5)
print(annplots$`2` + annplots$`4`)
dev.off()

```

## Figure 4 alt. 2
***

```{r}

design <- c(
  
  patchwork::area(1, 1, 2, 2),
  patchwork::area(1, 3, 2, 4),
  
  patchwork::area(3, 1, 7, 4),
  
  patchwork::area(1, 5, 1, 5),
  patchwork::area(1, 6, 1, 6),
  patchwork::area(2, 5, 2, 5),
  patchwork::area(2, 6, 2, 6),
  patchwork::area(3, 5, 3, 5),
  patchwork::area(3, 6, 3, 6),
  patchwork::area(4, 5, 4, 5),
  patchwork::area(4, 6, 4, 6),
  patchwork::area(5, 5, 5, 5),
  patchwork::area(5, 6, 5, 6),
  patchwork::area(6, 5, 6, 5),
  patchwork::area(6, 6, 6, 6),
  patchwork::area(7, 5, 7, 5),
  patchwork::area(7, 6, 7, 6)
  
)

p <-  
  patchwork::plot_spacer() +
  patchwork::plot_spacer() +
  gheat +
  factorplots$`2`$factor_12 +
  factorplots$`4`$factor_12 +
  factorplots$`2`$factor_2 +
  factorplots$`4`$factor_2 +
  factorplots$`2`$factor_11 +
  factorplots$`4`$factor_11 +
  factorplots$`2`$factor_1 +
  factorplots$`4`$factor_1 +
  factorplots$`2`$factor_16 +
  factorplots$`4`$factor_16 +
  factorplots$`2`$factor_6 +
  factorplots$`4`$factor_6 +
  factorplots$`2`$factor_7 +
  factorplots$`4`$factor_7 +
  patchwork::plot_layout(design = design, widths = c(1, 1, 1, 1, 1.5, 1.5))

pdf(file = "figure_6_patchwork_alt_2.pdf", width = 12, height = 15)
print(p)
dev.off()

```

